---
abstract: 'Path::Tiny types and coercions for Moose'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0.18
  File::pushd: 0
  List::Util: 0
  Test::Fatal: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Path-Tiny
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  MooseX::Types::Path::Tiny:
    file: lib/MooseX/Types/Path/Tiny.pm
    version: 0.005
requires:
  Moose: 2
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Stringlike: 0
  Path::Tiny: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/karenetheridge/moosex-types-path-tiny/issues
  homepage: https://metacpan.org/release/MooseX-Types-Path-Tiny
  repository: git://github.com/dagolden/moosex-types-path-tiny.git
version: 0.005
x_contributors:
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Toby Inkster <mail@tobyinkster.co.uk>'
